awdc

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -111,11 +111,21 @@ jobs:
         fi
         RUN=$CI_UTILS/roswell/run-test-forms.ros
         PASS=33
+        EXPECT=$PASS
         run_tests () {
           # expects -l package forms
           # to pass to run-test-forms
           echo "$RUN $*"
-          ( set +e ; $RUN -r $PASS $@ ; [ $? -eq $PASS ] )
+          ( set +e ; $RUN -r $PASS $@ )
+          local ret=$?
+          if [ $ret -eq $EXPECT ]
+          then
+            echo -e "\033[0;32mGot $ret, expected $EXPECT: OK\033[0m"
+            true
+          else
+            echo -e "\033[0;31mGot $ret, expected $EXPECT: BAD $fail\033[0m"
+            false
+          fi
         }
         EOF
         cat ~/.profile
