wADC

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -112,18 +112,19 @@ jobs:
         RUN=$CI_UTILS/roswell/run-test-forms.ros
         PASS=33
         EXPECT=$PASS
+        RET=-1
         run_tests () {
           # expects -l package forms
           # to pass to run-test-forms
           echo "$RUN $*"
-          local ret=-1
-          ( set +e ; $RUN -r $PASS $@ ; ret=$? ; true)
-          if [ $ret -eq $EXPECT ]
+          RET=-1
+          ( set +e ; $RUN -r $PASS $@ ; RET=$? ; true)
+          if [ $RET -eq $EXPECT ]
           then
-            echo -e "\033[0;32mGot $ret, expected $EXPECT: OK\033[0m"
+            echo -e "\033[0;32mGot $RET, expected $EXPECT: OK\033[0m"
             true
           else
-            echo -e "\033[0;31mGot $ret, expected $EXPECT: BAD $fail\033[0m"
+            echo -e "\033[0;31mGot $RET, expected $EXPECT: BAD $fail\033[0m"
             false
           fi
         }
